[programs.localnet]
game_metadata = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kelliott/.config/solana/id.json"

[scripts]
test = "ts-mocha -t 1000000 tests/*.ts"
