[programs.localnet]
battle_arena = "4RKZfwgWxUz1XEmgPnYkZTSQpzaKGPS9pnGbPTghbZyQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kelliott/.config/solana/id.json"

[scripts]
test = "ts-mocha -t 1000000 tests/*.ts"
